### ISSUE TITLE
GQ and PL should optionally be floats

### ISSUE THREAD

**Issue by ekg** [samtools/hts-specs#129] opened 2016-02-16 11:04 UTC
There is no clear reason to force GQ and PL to be integers. Would anyone object to allowing them to be floats? QUAL can be a float, and that seems useful. I don't see how it would be different for GQ and PL. This has no apparent benefit and is causing problems for VCF users.

**Comment by jkbonfield** [comment] 2016-02-16 13:38
On Tue, Feb 16, 2016 at 03:04:11AM -0800, Erik Garrison wrote:
> There is no clear reason to force GQ and PL to be integers. Would anyone object to allowing them to be floats? QUAL can be a float, and that seems useful. I don't see how it would be different for GQ and PL. This has no apparent benefit and is causing problems for VCF users.

It depends on whether the additional fidelity actually useful.  Eg
raw base call confidence values could easily be a float too, but
ultimately even the integer phred score was deemed too fine grained
and further quantisation is now the norm.

I don't have any issue with using floats where appropriate. What are
the problems currently caused by using integers?

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by yfarjoun** [comment] 2016-05-08 23:48
There is a reason to keep them integers: file size. Integers compress much better than floats. Given that we do not really need GQ or PL in higher resolution than ints (as far as I know) I do not see the benefit of moving to floats, but I see the disadvantages. 

I'm not sure that there's much utility in QUAL being a float either, could you elaborate where that is useful?

**Comment by d-cameron** [comment] 2016-05-09 01:58
I'm looking at doing quality score recalibration on SV callers and float-scale QUAL score are absolutely required. Given most SV callers have at least at a 10% FDR, an int scale QUAL score would quantise everything into 10 possible values. I'll argue strongly against forcing a variant with a 10% chance of being correct into the same bucket as a variant with 0.1% chance for the sake of file size. Some examples of the utility of floats are: a) choosing whether to perform follow-up validation of an otherwise promising candidate mutation; and b) identifying variants in from low-coverage data (ie: noisy with with high FDR), or with prior knowledge (eg: transgene validation).

I can live with htsjdk truncating at 2dp and not being able to round-trip QUAL values, but if int QUAL values were to be used, I'd be forced to create a float QUAL INFO field in all my VCFs and use that instead.

**Comment by d-cameron** [comment] 2016-05-09 02:06
> It depends on whether the additional fidelity actually useful.  Eg
raw base call confidence values could easily be a float too, but
ultimately even the integer phred score was deemed too fine grained
and further quantisation is now the norm.

I would argue that being able to differentiate between a clinically actionable variant having a 10% chance of being correct, a 0.1% chance of being correct, and a 0% chance of being correct is extremely important.

**Comment by eitanbanks** [comment] 2016-05-09 16:35
Hi @d-cameron, I think you may be misunderstanding the proposal.  There is no doubt that the QUAL field needs to remain as a float.  That's a given.
The question was whether the PLs and GQs should be floats.  There is absolutely no reason to change PLs to be floats because there's already a keyword reserved for such things: GL.  We used to use GLs all the time... until our VCFs started containing many samples and were genome wide.  Then we (the 1000 Genomes project) realized that it was a terrible idea: the extra resolution over ints added nothing other than massively bloated file sizes, so we introduced the PL tag as an alternative.
I cannot express enough how badly GLs scale.  This is a format-level field, so there's one for every sample.  And there are multiple numbers for each sample, so it gets big quickly.
I don't see how integer-based PLs could be causing problems for users.  But if you want to use GLs then go ahead (NOT RECOMMENDED).

**Comment by eroller** [comment] 2017-10-19 20:46
@eitanbanks why do you make a distinction between QUAL needing to be float but GQ not? They are both phred-scaled probabilities. Is it just that you expect these values to be on different scales so that QUAL needs higher resolution while GQ does not?

I also don't understand the problem regarding the file size, If the type were float, the VCF creator is still able to round their values to the nearest integer before writing out and it should be the same file size as if you used int type. The only change is in the VCF header line describing the type of the GQ field.

If your concern with file size is regarding the binary format BCF then that does get more complicated. I did notice, however, in the current spec that integers can be encoded as either 8, 16, or 32 bit values with the encoder free to choose the appropriate range. So why not also allow floats to be encoded as either 8, 16, or 32 bit integers or the standard 32 bit IEEE-754-1985 single-precision value. The encoder is free to choose the best representation to achieve the smallest file size and for your use case where GQ only needs to be integers then the file size would be identical.

**Comment by lh3** [comment] 2017-10-19 21:34
We are talking about the BCF2 file size, not VCF. BCF2 always uses 32-bit float, but these values can't be compressed well. There is only one QUAL per line. There can be thousands of PL/GQ per line. Their sizes matter a lot more.

Does VCF spec allow predefined tag to have different types? If not, we have to come up with new tags for floating point genotype quality. The cost of changing the existing GQ is too high.

**Comment by lh3** [comment] 2017-10-19 21:36
I will close this issue now. Someone can send a new pull request for a floating point GQ equivalent.

**Closed by lh3** 2017-10-19 21:36 UTC
Labels: vcf

**Comment by eroller** [comment] 2017-10-20 18:45
32-bit float can be compressed just as well as 32-bit integer given the same range and precision of the data being compressed. Given a large dataset that contains a set of integers `{1, 2, 3, 4, 5}` vs. a set of floats `{1.00000, 2.00000, 3.00000, 4.00000, 5.00000}` I would expect gzip to compress the file containing floats to roughly the same size as the file containing integers. It should be up to the VCF/BCF creator to decide the range and precision of the data they want to encode. That decision will directly affect the size of the file produced. The spec should not be confining certain fields that are conceptually floating point to have integer values simply because their use case only required integers.

I understand the difficulty with changing GQ at this point, but please consider using float for any new  fields that are added to the spec when those fields conceptually may be floating point (e.g. probabilities).

**Comment by pd3** [comment] 2017-10-20 18:54
The integer fields in BCF can be coded in 8, 16 or 32 bits. For FORMAT fields with many samples this makes a difference.

**Comment by eroller** [comment] 2017-10-20 20:24
So why not permit float fields to be encoded as 8, 16 or 32 bit integers as well? In fact, I see nothing in the spec that specifically prohibits this since the type is specified in the lower 4 bits of each and every encoded value.

I think the critical point here is that the specification controls how third party tools are to interpret the values of specific fields. Quality scores are probabilities which are inherently fractional, not integer. By separately defining how fields should be interpreted vs. how they are encoded, the specification can enable users to make their own trade-off between range/precision and file size.

A custom tag is not a great option because it means my file will not be compatible with third party tools.

**Comment by lh3** [comment] 2017-10-20 21:10
This is a good suggestion. It could have worked if we had it baked in bcf2 at the beginning. However, it is too late now. User code may not expect an integer array when it is defined as float in the header. It is not worth taking the risk for a minor improvement. The best solution now is to propose a new tag.

Quality scores had always been integers. VCF QUAL is the only exception.
