### ISSUE TITLE
Gathering contig information from CSI files

### ISSUE THREAD

**Issue by mliezun** [samtools/hts-specs#611] opened 2021-12-02 17:13 UTC
We have been trying to implement a tool for reading portions of a VCF file using a CSI index. We want to implement something like -r chr:beg-end|chr, but we see that there is no contig information in the CSI file as per this spec https://samtools.github.io/hts-specs/CSIv1.pdf

Could you help me figure this out? Or point me in the right direction?

**Comment by mliezun** [comment] 2021-12-02 18:17
Thank you John, I will take a closer look to the tabix spec and the source code to see if we can solve this

**Comment by jkbonfield** [comment] 2022-01-06 09:36
Closing as duplicate of #70.

**Closed by jkbonfield** 2022-01-06 09:36 UTC
Labels: duplicate
