### ISSUE TITLE
SAM mapping position field

### ISSUE THREAD

**Issue by gt1** [samtools/hts-specs#195] opened 2017-03-17 10:38 UTC
The SAM spec defines the pos field as "1-based leftmost mapping POSition of the first matching base" (section 1.4 in the current document). I assume this refers to the first M/=/X operation in the cigar string. Is this correct? If so, could that be stated explicitly in the document?

**Comment by jkbonfield** [comment] 2017-03-17 11:22
Agreed it isn't clear. Specifically "matching base" could be interpreted to rule out 100M cigar where the first base disagrees with the reference.  (Most aligners would emit 1S 99M of course, but that's not a guaranteed and after realignment to other reads it may be the first base is a SNP that all reads agree on so is correctly part of the alignment.)

I think in theory it could also refer to a D or N operator too - anything anchored to a reference location basically - although again it's unlikely to be a common alignment output.  Conversely a read starting with an insertion (which is a valid and possible after multiple-realignment) is before the POS.

Maybe therefore it is appropriate to describe this in terms of the position of the first base with a cigar operator that is anchored to a reference location, ie everything except cigar I, S, H and P.

**Comment by jmarshall** [comment] 2017-04-05 13:38
Duplicate of #80 — see previous commentary there.

**Comment by jkbonfield** [comment] 2017-04-05 16:39
Thanks John, closing as dup.  Please add comments to #80  instead.

**Closed by jkbonfield** 2017-04-05 16:39 UTC
Labels: duplicate, sam
